// export const stats = [
//     {
//       title: "Tổng nhân viên",
//       value: "500",
//       change: "10,2%",
//       isPositive: true,
//     },
//     {
//       title: "Nhân viên mới",
//       value: "1.080",
//       change: "6,2%",
//       isPositive: true,
//     },
//     {
//       title: "Nhân viên đã nghỉ",
//       value: "80",
//       change: "0,2%",
//       isPositive: false,
//     },
//     {
//       title: "Ứng viên trong tháng",
//       value: "140",
//       change: "3,4%",
//       isPositive: true,
//     },
//   ];

//  export const employees = [
//     {
//       name: "Nguyễn Thị An",
//       email: "nguyenthian@example.com",
//       avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=An",
//       daysOff: 56,
//       salary: "5.600.000",
//       status: "Đã đóng" as const,
//     },
//     {
//       name: "Nguyễn Minh Lương",
//       email: "nguyenminluong@example.com",
//       avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Luong",
//       daysOff: 22,
//       salary: "2.200.000",
//       status: "Đã đóng" as const,
//     },
//     {
//       name: "Nguyễn Văn Chiếu",
//       email: "nguyenvanchieu@example.com",
//       avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chieu",
//       daysOff: 15,
//       salary: "1.600.000",
//       status: "Chưa đóng" as const,
//     },
//     {
//       name: "Marvin McKinney",
//       email: "marvin.mckinney@example.com",
//       avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marvin",
//       daysOff: 13,
//       salary: "1.300.000",
//       status: "Đã đóng" as const,
//     },
//     {
//       name: "Brooklyn Simmons",
//       email: "brooklyn.simmons@example.com",
//       avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Brooklyn",
//       daysOff: 7,
//       salary: "700.000",
//       status: "Chưa đóng" as const,
//     },
//     {
//       name: "Kristin Watson",
//       email: "kristin.watson@example.com",
//       avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kristin",
//       daysOff: 4,
//       salary: "400.000",
//       status: "Đã đóng" as const,
//     },
//     {
//       name: "Devon Lane",
//       email: "devon.lane@example.com",
//       avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Devon",
//       daysOff: 1,
//       salary: "100.000",
//       status: "Chưa đóng" as const,
//     },
//   ];

//  export  interface Employee {
//   no: number;
//   id: string;
//   fullname: string;
//   role: string;
//   phone: string;
//   email: string;
//   signDay: string;
// }

// export const initialEmployees: Employee[] = [
//   {
//     no: 1,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Developer",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 2,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 3,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 4,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 5,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 6,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 7,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 8,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 9,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 10,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 11,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 12,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 13,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 14,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
//   {
//     no: 15,
//     id: "acc006",
//     fullname: "Nguyen Thanh A",
//     role: "Sale",
//     phone: "0912345678",
//     email: "nta@911.com",
//     signDay: "22/12/2020",
//   },
// ];

